server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
    web:
      # 路径配置
      base-path: /manage
      # 暴露的端点
      exposure:
        include: 'info,health,env,beans,date'
      # 跨域配置
      cors:
        allowed-origins: "https://example.com"
        allowed-methods: "GET,POST"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
    date:
      enabled: true
knife4j:
  enable: true